# index:
#    path: /
#    controller: App\Controller\DefaultController::index

# ----------------------------- ROUTES STATIQUES ------------------------------------------

app_about_us:  
    path: /aboutus
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: "static/about-us.html.twig"

app_how_it_works:  
    path: /howitworks
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: "static/how_it_works.html.twig"

app_faq:  
    path: /faq
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: "static/faq.html.twig"

app_legal_notice:  
    path: /legal_notice
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: "static/legal-notice.html.twig"

app_disclaimer:  
    path: /disclaimer
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: "static/disclaimer.html.twig"

app_privacy_policy:  
    path: /privacy_policy
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: "static/privacy-policy.html.twig"